sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t benshidanny11/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true benshidanny11/docker-react npm run test
